config/routes.rb
Todo::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :authentications
  root :to => "authentications#index"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  validates :provider, :presence => true, :uniqueness => { :scope => :user_id }

  def provider_name
    provider == 'open_id' ? "OpenID" : provider.titleize
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :authentications

  attr_accessible :email

  devise :database_authenticatable, :registerable,  :trackable, :validatable

  def password_required?; false; end

  def apply_omniauth(omniauth)
    self.email = extract_email(omniauth) if email.blank?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  private

  def extract_email(omniauth)
    if omniauth['provider'] == 'facebook'
      omniauth['extra']['user_hash'].try(:[],'email')
    else
      omniauth['user_info']['email']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  has_mobile_fu
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/authentications/index.html.erb
<% title "Sign In Options" %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You have signed in with these services:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "omniauth/#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider_name %></div>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "omniauth/twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "omniauth/facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google" class="auth_provider">
  <%= image_tag "omniauth/google_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<a href="/auth/yahoo" class="auth_provider">
  <%= image_tag "omniauth/yahoo_64.png", :size => "64x64", :alt => "OpenID" %>
  OpenID
</a>
<div class="clear"></div>

app/views/authentications/index.mobile.erb
<% content_for :title do %>
  Review Umpire
<% end %>

<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="b">
	<li data-role="list-divider">Login </li>
	<li> 
    <%= image_tag "omniauth/facebook_64.png", :size => "64x64", :alt => "Facebook" %>
    <h3><%= link_to "Facebook", "/auth/facebook", :rel => "external"%></h3>
		<p>Facebook</p> 
	</li> 
	<li> 
    <%= image_tag "omniauth/google_64.png", :size => "64x64", :alt => "google" %>
    <h3><a href="/auth/google" rel="external">Google</a></h3>
		<p>Google</p>
	</li> 
	<li> 
    <%= image_tag "omniauth/yahoo_64.png", :size => "64x64", :alt => "yahoo" %>
    <h3><a href="/auth/yahoo" rel="external">Yahoo</a></h3>
		<p>Yahoo</p>
	</li> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>.<br />
          Not you? <%= link_to "Sign out", destroy_user_session_path %>
        <% else %>
          <%= link_to "Sign In", authentications_path %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html> 
<html> 
  <head> 
    <title>Review Umpire</title> 
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css" />
    <script src="http://code.jquery.com/jquery-1.4.3.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js"></script>
    <%= javascript_include_tag 'rails' %>
  </head> 
  <body> 
    <div data-role="page">

      <div data-role="header" data-position="inline">
        <a href='#' class='ui-btn-left ui-btn-back' data-icon='arrow-l'>Back</a>
        <h1><%= content_for :title %></h1>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path %>
        <% end %>
      </div><!-- /header -->


      <div data-role="content">	
        <%= yield %>
      </div><!-- /content -->

    </div><!-- /page -->
  </body>
</html>